### ISSUE TITLE
Renaming methods and properties. 

### ISSUE THREAD

**Issue by michalskibinski109** [Disservin/chess-library#100]
There is really popular chess [library for python](https://python-chess.readthedocs.io/en/latest/). I believe all methods have much better names there. For example instead of 
`board.makeMove` you could use `board.push`. It is shorter and more intuitive. You are pushing `Move` object. Then you can `board.pop` If you want.

**Comment by Disservin** [comment]
Mh I am not sure, this would be a breaking change for everyone, and `makeMove` is a pretty common name in chess engines. python-chess indeed uses .push and has other names as well, but tbh i haven't see people use these names in real engines anyway... also the author of the python-chess library seems to have moved away from "push" to "play" for his rust library https://github.com/niklasf/shakmaty anyway
