### ISSUE TITLE
Illegal fen can also generate steps through chess::movegen::legalmoves

### ISSUE THREAD

**Issue by zx950921** [Disservin/chess-library#123]
For example: 8/7R/k2R1P2/p3p3/P3N3/8/1P3K2/8 w - - 16 71
![image](https://github.com/user-attachments/assets/86f64152-9356-4967-8b6d-ec76cbf54414)

This fen sets the white move, but the white has already checked the black

Is there any way I can detect this illegal fen in advance?

**Comment by Disservin** [comment]
If it is a game then you need gameover checks, otherwise you need to come um with your one logic to detect illegal fens.

**Comment by zx950921** [comment]
Thanks
