### ISSUE TITLE
Does not compile with #define DEBUG

### ISSUE THREAD

**Issue by vladkvit** [Disservin/chess-library#133]
When including chess.hpp and defining DEBUG, the file does not build. The cause is that `squareToString` is not defined.

Here is the relevant chunk around line 4788:

```
#ifdef DEBUG
        std::stringstream ss;

        ss << "pt " << int(info.piece) << "\n";
        ss << "info.from_file " << int(info.from_file) << "\n";
        ss << "info.from_rank " << int(info.from_rank) << "\n";
        ss << "promotion " << int(info.promotion) << "\n";
        ss << "to_sq " << squareToString[info.to] << "\n";

        std::cerr << ss.str();
#endif
```

squareToString does not appear anywhere else in the project. My recommendation would be to either remove the offending line or to reimplement squareToString.

**Comment by Disservin** [comment]
Hi, thanks for finding this, I've removed the code since it doesn't have much value now anyway.
