### ISSUE TITLE
UNMAKEMOVE a PROMOTIONMOVE is WRONGGGG

### ISSUE THREAD

**Issue by hikito-otikih** [Disservin/chess-library#136]
i tried to unmakemove a promotionmove and the board chess is added a rook : )?

**Comment by Disservin** [comment]
Then it probably was not a legal promotion move, can you show the code please ?

**Comment by hikito-otikih** [comment]
ERROR
UDSm53 - Online Java Compiler & Debugging Tool - Ideone.com<https://ideone.com/UDSm53>
You can see that, in this code, i use type 0 for MOVE and type 1 for UNMOVE.
[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/docx_16x16.png]listmove.docx<https://studenthcmusedu-my.sharepoint.com/:w:/g/personal/24125020_student_hcmus_edu_vn/ETwHZBBz4LZCshDjiK29oGEBeVm5jV2cUubADvdAlCUKqQ>
See listmove, it's a context.
________________________________

**Comment by hikito-otikih** [comment]
Ah and  an other wrong is after draw, board is keeping generating the valid move.
________________________________

**Comment by Disservin** [comment]
The problem is that `uciToMove` requires the move to be a valid move for the current board. Your uciToMove in unmakeMove tries to parse the move like it was a valid move which could be played on the board, which isnt the case because it was already played. So if you want to undo previous moves you have to store the moves in a stack and then take the last move from the stack and undo that.

**Comment by winapiadmin** [comment]
> ERROR
> UDSm53 - Online Java Compiler & Debugging Tool - Ideone.com<https://ideone.com/UDSm53>
> You can see that, in this code, i use type 0 for MOVE and type 1 for UNMOVE.
> [https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/docx_16x16.png]listmove.docx<https://studenthcmusedu-my.sharepoint.com/:w:/g/personal/24125020_student_hcmus_edu_vn/ETwHZBBz4LZCshDjiK29oGEBeVm5jV2cUubADvdAlCUKqQ>
> See listmove, it's a context.
> […](#)

You're using Java for C++ chess-library:)

**Comment by hikito-otikih** [comment]
No, I used C++ not Java, let’s see my example carefully.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: winapiadmin ***@***.***>
Đã gửi: Thursday, February 6, 2025 9:29:35 PM
Đến: Disservin/chess-library ***@***.***>
Cc: HUỲNH CHÍ TÔN ***@***.***>; Author ***@***.***>
Chủ đề: Re: [Disservin/chess-library] UNMAKEMOVE a PROMOTIONMOVE is WRONGGGG (Issue #136)


ERROR
UDSm53 - Online Java Compiler & Debugging Tool - Ideone.comhttps://ideone.com/UDSm53
You can see that, in this code, i use type 0 for MOVE and type 1 for UNMOVE.
[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/docx_16x16.png]listmove.docxhttps://studenthcmusedu-my.sharepoint.com/:w:/g/personal/24125020_student_hcmus_edu_vn/ETwHZBBz4LZCshDjiK29oGEBeVm5jV2cUubADvdAlCUKqQ
See listmove, it's a context.
…

You're using Java for C++ chess-library:)

**Comment by winapiadmin** [comment]
> No, I used C++ not Java, let’s see my example carefully.
> 
> Tải Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

You use Java JVM for C++? ("Online Java Compiler" in the title)
