### ISSUE TITLE
Doubly Disambiguated Moves Not Displayed Correctly in Generate Moves in Algebraic Notation

### ISSUE THREAD

**Issue by ivan-cunha** [Disservin/chess-library#140]
# Description
In certain scenarios where moves require double disambiguation (e.g., two pieces of the same type can move to the same square, and both their ranks and files need to be specified), the moves are not displayed correctly in the algebraic notation output.

# Example

```#include "chess.hpp"

using namespace chess;
using namespace std;
int main () {
    Board board = Board("2N1N3/p7/6k1/1p6/2N1N3/2R5/R3Q1P1/2R3K1 w - - 5 55");

    Movelist moves;
    movegen::legalmoves(moves, board);

    for (const auto &move : moves) {
        //std::cout << uci::moveToUci(move) << std::endl;
        cout << uci::moveToSan(board, move) << endl;
    }

    return 0;
}
```

Output:

Kf1
Kh1
Kf2
Kh2
g3
g4
Nb2
Ncd2
Na3
Ne3
Na5
Ne5+
N4b6
Ncd6
Ned2
Nf2
Ng3
Nc5
Ng5
**Ned6**
N4f6
N8b6
N8d6
Nxa7
Ne7+
**Ned6**
N8f6
Nc7
Ng7
Rca1
Rb1
Rd1
Re1
Rf1
Rcc2
Raa1
Rb2
Rac2
Rd2
Raa3
Ra4
Ra5
Ra6+
Rxa7
R3c2
Rca3
Rb3
Rd3
Re3
Rf3
Rg3+
Rh3
Qd1
Qe1
Qf1
Qb2
Qc2
Qd2
Qf2
Qd3
Qe3
Qf3
Qg4+
Qh5+
![Captura de tela 2024-12-16 210726](https://github.com/user-attachments/assets/d4ec0efb-3b8d-465e-a446-c2d7b3db3a38)

In this case, the moves need to be Doubly Disambiguated (Ne1d6 or Ne4d6).

**Comment by Disservin** [comment]
Hi thanks for reporting this. Should be fixed in the latest version.
