### ISSUE TITLE
pgn::StreamParser fails when game ends before first move

### ISSUE THREAD

**Issue by Parranoh** [Disservin/chess-library#68]
My PGN file, taken from [Lichess](https://database.lichess.org/):

```
[Event "Rated Blitz tournament https://lichess.org/tournament/UnR37DjL"]
[Site "https://lichess.org/PqdJBiQ3"]
[Date "2023.12.01"]
[Round "-"]
[White "eliasevinotintos"]
[Black "bianney1963"]
[Result "0-1"]

 0-1

```

When I try to parse this with `pgn::StreamParser`, it skips `0` as the move counter, then parses `-1` as a move, and finally tries to read a second move until it reaches EOF (or finds the next `[Event` two lines down).

[This patch](https://github.com/Disservin/chess-library/files/14110273/detect-immediate-game-termination.txt) fixes the issue for me, but the code isn't very pleasant to look at.

**Comment by Disservin** [comment]
Thanks, I will have a look.

**Comment by Disservin** [comment]
Should be fixed now.

**Comment by Disservin** [comment]
Uh yikes... let me check
