### ISSUE TITLE
Board::us() not properly displaying the perspective of the board.

### ISSUE THREAD

**Issue by fqhd** [Disservin/chess-library#78]
I imagine Board::us() is supposed to return the bitboard from the perspective of the player that currently has to play a move. This is not what is happening, it seems that no matter who's turn it is, Board::us() will always make black appear on the bottom and white on top(both on the stringified version of Board::us() and the actual bitboard data itself, I checked manually). Same thing applies to Board::them(), the person's turn has no effect on the direction of the bitboard returned.

**Comment by Disservin** [comment]
Running the unit tests I get this representation.

For a bitboard which has the Square A1 set.
`Bitboard::fromSquare(Square::underlying::SQ_A1);`
```
../tests/bitboard.cpp:297: SUCCESS: CHECK( static_cast<std::string>(str1) == str1 ) is correct!
  values: CHECK( 00000000
00000000
00000000
00000000
00000000
00000000
00000000
10000000
 == 0x560cc950f420 )
```

and this for Square A2
`Bitboard::fromSquare(Square::underlying::SQ_A2);`

```
../tests/bitboard.cpp:301: SUCCESS: CHECK( static_cast<std::string>(str2) == str2 ) is correct!
  values: CHECK( 00000000
00000000
00000000
00000000
00000000
00000000
00000000
01000000
 == 0x560cc950f498 )
 ```

So I don't see anything wrong atm.

**Comment by fqhd** [comment]
> Oh you are talking about the direction? The direction obviously doesn’t change.
> 
> Each bit of the bitboard is representing a square on the chess board. ![image](https://private-user-images.githubusercontent.com/45608332/307880684-97522c20-34c4-4807-b9c4-697dabf7fb6c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjUyNzYsIm5iZiI6MTcxMTQ2NDk3NiwicGF0aCI6Ii80NTYwODMzMi8zMDc4ODA2ODQtOTc1MjJjMjAtMzRjNC00ODA3LWI5YzQtNjk3ZGFiZjdmYjZjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjI0NTExYzQwOWYwYWQ3OTk1N2Q3YmY1MmJlMzczZjQ3ZDJlMjA1OTdmNTcxNTJmNTcwNzA2YmQzOWZkOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hdL_71sadYF-bvL17M5tJLAfO88S2EVs6ng5I6TPKjo)
> 
> which matches these squares.
> 
> ![image](https://private-user-images.githubusercontent.com/45608332/307880865-67ac3282-8937-4049-8e84-3a4a1435dc57.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjUyNzYsIm5iZiI6MTcxMTQ2NDk3NiwicGF0aCI6Ii80NTYwODMzMi8zMDc4ODA4NjUtNjdhYzMyODItODkzNy00MDQ5LThlODQtM2E0YTE0MzVkYzU3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmIyMjAxYmZjZjlmNGUzNDAwNGQ1NzVjZDUyOGZmNTE3OTEwNWRhZDhhYWRkZDljMjkyNWU4ZTUyOWYyYzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sowZ2tnJNmeMQs6yBPgzS5ltr7JxXSSfbIkOE4TPrdU)
> 
> White should be on the bottom. Not sure how if my stringification is currently displaying it on the bottom as well. Gotta check that later, but one side will always be on the bottom and the other on the top. The players turn shouldn’t have an effect on that

Interesting okay. Then what is the point of having board.them and board.us?

**Comment by Disservin** [comment]
To get the underlying bitboards to do operations on them? 
You can get your bitboard (us) and their (them) bitboard. Since ~us` isn't equivalent to `them`. They are not just for visualization but are at the low level the basis of how moves and the board is represented in an efficient way. https://www.chessprogramming.org/Bitboards

**Comment by fqhd** [comment]
Yes but there is a color parameter that you pass to both us and them. If the direction of the board doesn't change when calling us or them(aka white is always on the bottom), then what's the point of having two separate functions?

**Comment by Disservin** [comment]
Ah, mh good point.. I think some time ago it didn't take a color parameter, so yeah, might also be more self explanatory if you write `board.them(c);` instead of `board.us(~c);` perhaps?

**Comment by fqhd** [comment]
I see okay, personally I suggest having just one function `Bitboard getBitboard(Color color) const;` function to avoid confusion? maybe that's a good change idk
