### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by codingbear314** [Disservin/chess-library#82]
"message": "no suitable conversion function from \"std::_Array_iterator<chess::Movelist::value_type, 256Ui64>\" to \"chess::Movelist::iterator\" exists",
"source": "C/C++",
"startLineNumber": 1268

I'm getting this message in vscode, with gcc 8.1.0

**Comment by codingbear314** [comment]
Sorry I think I fixed it

**Comment by jpmorenorj** [comment]
Hey, how did you fix it?

**Comment by Disservin** [comment]
should be fixed now in upstream
