### ISSUE TITLE
sidetomove function unintuitive interaction

### ISSUE THREAD

**Issue by galuxes** [Disservin/chess-library#84]
Hello I am making a chess bot right now and I needed to check who's turn it is so I used the "sideToMove" function inside the chess::Board class and I've noticed it return the opposite color I expected as it returns black when it is white's turn and vice versa.

**Comment by Disservin** [comment]
Do you have an example for me?

**Comment by Disservin** [comment]
i.e.
```cpp
    auto board = Board();
    std::cout << board.sideToMove() << "\n";
```
returns
```
w
```
